- hosts: 127.0.0.1
  connection: local
  vars:
    output_folder: /tmp/docker-build-output
    docker_temp_build_folder: /tmp
  tasks:
    - name: Include variables
      include_vars:
        file: configuration.yml
        name: config
    - name: create target folder
      file:
        path: "{{ docker_temp_build_folder }}/proxmox-prometheus-exporter"
        state: directory
    - name: copy build files
      copy:
        src: "{{ playbook_dir }}/{{ item }}"
        dest: "{{ docker_temp_build_folder }}/proxmox-prometheus-exporter"
      with_items:
        - common
        - exporter
        - go.mod
        - go.sum
        - main.go
        - configuration.yml
        - Dockerfile
    - name: copy secrets file inside the folder
      copy:
        src: "{{ config.secrets_file_path }}"
        dest: "{{ docker_temp_build_folder }}/proxmox-prometheus-exporter/secrets.yml"
    - name: change config file to point to the proper secret file
      lineinfile:
        path: "{{ docker_temp_build_folder }}/proxmox-prometheus-exporter/configuration.yml"
        regexp: 'secrets_file_path:.*'
        line: "secrets_file_path: secrets.yml"
    - name: make sure the output folder exists
      file:
        path: "{{ output_folder }}"
        state: directory
    - name: build image
      community.docker.docker_image:
        tag: pve-exporter:v1
        source: build
        build:
          path: "{{ docker_build_folder }}/proxmox-prometheus-exporter/Dockerfile"
        archive_path: "{{ output_folder }}"
      become: yes

    