- hosts: 127.0.0.1
  connection: local
  vars:
    docker_temp_build_folder: /tmp
  tasks:
    - name: Include variables
      include_vars:
        file: configuration.yml
        name: config
    - name: create target folder
      file:
        path: "{{ docker_temp_build_folder }}/proxmox-prometheus-exporter"
        state: directory
    - name: copy build files
      copy:
        src: "{{ playbook_dir }}/{{ item }}"
        dest: "{{ docker_temp_build_folder }}/proxmox-prometheus-exporter"
      with_items:
        - common
        - exporter
        - go.mod
        - go.sum
        - main.go
        - configuration.yml
        - Dockerfile
    - name: copy secrets file inside the folder
      copy:
        src: "{{ config.secrets_file_path }}"
        dest: "{{ docker_temp_build_folder }}/proxmox-prometheus-exporter/secrets.yml"
    - name: change config file to point to the proper secret file
      lineinfile:
        path: "{{ docker_temp_build_folder }}/proxmox-prometheus-exporter/configuration.yml"
        regexp: 'secrets_file_path:.*'
        line: "secrets_file_path: /pve-exporter/config/secrets.yml"
    - name: change main.go file to point to the proper configuration path
      lineinfile:
        path: "{{ docker_temp_build_folder }}/proxmox-prometheus-exporter/main.go"
        regexp: 'const configurationFilePath =.*'
        line: 'const configurationFilePath = "/pve-exporter/config/configuration.yml"'
    - name: build image
      community.docker.docker_image:
        name: pve-exporter
        tag: latest
        source: build
        build:
          path: "{{ docker_temp_build_folder }}/proxmox-prometheus-exporter"
        archive_path: "pve-exporter.tar"
      become: yes
    - name: remove intermediate images
      community.docker.docker_prune:
        images: yes
        images_filters: 
          label: "stage=builder"
      become: yes
    - name: remove temporary build folder
      file:
        path: "{{ docker_temp_build_folder }}/proxmox-prometheus-exporter"
        state: absent

    